pipeline {
  agent any

  stages {
    stage('build') {
      steps {
        sh './gradlew build --stacktrace'
      }
    }

    stage('test') {
      steps {
        sh './gradlew test --stacktrace'
      }
    }

    stage('deploy') {
      steps {
        sh 'git push https://heroku:$HEROKU_API_KEY@git.heroku.com/jenkins-pipeline.git master'
      }
    }
  }
}
