pipeline {
  agent any

  stages {
    stage('build') {
      steps {
        sh './gradlew build --stacktrace'
      }
    }

    stage('test') {
      steps {
        sh './gradlew test --stacktrace'
      }
    }

    stage('deploy') {
      steps {

      }
    }
  }
}
